name: Build
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile.php

env:
  DOCKER_BUILDKIT: 1

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  php:
      name: "${{ matrix.version }}"
      runs-on: ubuntu-latest
      strategy:
        matrix:
          version:
            - 8.2
            - 8.3
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login into Github Docker Registery
          run: echo "${{ secrets.QUAY_ROBOT_PASSWORD }}" | docker login quay.io -u friendsofshopware+devcontainer_gh_actions --password-stdin

        - name: Install and configure Namespace CLI
          uses: namespacelabs/nscloud-setup@v0

        - name: Configure Namespace powered Buildx
          uses: namespacelabs/nscloud-setup-buildx-action@v0

        - uses: docker/build-push-action@v5
          with:
            tags: quay.io/friendsofshopware/devcontainer:base-${{ matrix.version }}
            platforms: linux/amd64,linux/arm64
            file: Dockerfile.php
            build-args: |
              PHP_VERSION=${{ matrix.version }}
            push: true
            provenance: false
